### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by qq522384337** [zeptofine/node-quick-maths#1]
制作成节点组并没有链接到对应的值
![Snipaste_2024-07-29_03-57-15](https://github.com/user-attachments/assets/1ff38f1b-34e2-4f0b-8c05-1d34452a86a6)

**Comment by zeptofine** [comment]
wow, this is kind of embarassing! it was a single line fix. Could you please try this hotfix? If it works I'll push it to the website.

Attempted auto-translation: 
哇，这有点尴尬！只是一行代码的修复。你能试试这个热修复吗？如果工作正常，我会将它推送到网站上。

https://github.com/zeptofine/node-quick-maths/releases/tag/1.2.1

**Comment by zeptofine** [comment]
Confirmed it on my end. Seems to have fixed the issue. Uploaded it to the site.

---

已在我的这边确认。似乎已经解决了问题。已将其上传至网站。
